#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by pcmdi9.llnl.gov - 2015/04/02 13:15:27
# Search URL: http://pcmdi9.llnl.gov/esg-search/wget/?query=variable:tasmax OR variable:tasmin OR variable:tas OR variable:ps OR variable:huss OR variable:pr OR variable:rlds OR variable:rsds OR variable:sfcWind&dataset_id=cmip5.output1.MRI.MRI-CGCM3.historical.day.atmos.day.r1i1p1.v20120701|dias-esg-nd.tkl.iis.u-tokyo.ac.jp
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://pcmdi9.llnl.gov/esg-search/wget/?query=variable:tasmax OR variable:tasmin OR variable:tas OR variable:ps OR variable:huss OR variable:pr OR variable:rlds OR variable:rsds OR variable:sfcWind&dataset_id=cmip5.output1.MRI.MRI-CGCM3.historical.day.atmos.day.r1i1p1.v20120701|dias-esg-nd.tkl.iis.u-tokyo.ac.jp'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' 'e0f82d2a3ce73a17d5a48efe7c3bece8'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' '2095436d57c78e11359ee1975f71db59'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' '241d30892232830de450b054a487b533'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' 'e8e7380ccd7feeaf40c4258cd9fcdf52'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' 'a7b8a03e33d6226dc6bd90b2f2512e66'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '1a6d800e389f8be42389f141d8d45261'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'MD5' '129b1cec971607b8e3133824aa72bb19'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'MD5' '8da22fb0497555d4d3dd7cf3a36b33e8'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'MD5' 'c7f66f20197f0a1619f4a0113e341b59'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'MD5' 'f09d2cb2aeedbd629d948dd2ee4e2b49'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'MD5' 'cd86c5fea599b40898597035756445e1'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'MD5' '35eb9a956a10ba5fbd8b9ac9f2ef2216'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'MD5' '815cb57bf83bb48a6584e8e3f0f893c3'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'MD5' 'ac55d841e471e07a4baf40f1a06d2736'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'MD5' 'f42afa1db40ac7cea070eb8975c3670f'
'sfcWind_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/sfcWind/sfcWind_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'MD5' '2f93b8106f3d2c428b0b2e8b186c37c3'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' 'e0804714becc9dd430ea16569c59e173'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' 'e56fefb47f7af5bd7332a864568fac28'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' '61bebb100efce6835c20123d92a1d2b4'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' 'd624fb7ad3ab9ad9b67a189171d3436c'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' 'b00e161c73d5166a1fe72318bb394090'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '8d09c7b0ec7cf2aa569fca19bf981f37'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'MD5' '3e239a6328caf61f3d8d13cdc9fab32e'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'MD5' 'dc9db39711f0068922f07b1d272cb30e'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'MD5' '7ac3d8301a5e87218feeca8e1773d06c'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'MD5' 'e392b880a956789a7eaf42fa3a3348eb'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'MD5' 'a204998aaa3e5f05fc6ec890f3eca107'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'MD5' '402bb8413c97ece8e525135b5a024687'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'MD5' '2129835541a0809da6b8bd4bf059c1b6'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'MD5' '328e275f9c88c8bbca59f3172d633c0e'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'MD5' 'e13d62c572f8a0f6a6b4b4acb4ae8aa3'
'tasmin_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmin/tasmin_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'MD5' '93a7a2b50c116090073617f51209fdd4'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' '0591ca8ee6ebf4524a280b2e36345a4f'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' '46600863cd4dc182cdd86b0a0004d32d'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' '09413e67e2443a0ffadf6e9b3e1a36cb'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' 'b00bc48e17b553d6d00d734d9241951f'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' 'a0fd8d028607f22d3e257ba94a9028fa'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '868bf8ed66186655b713d96b0ae11a90'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'MD5' 'ce25cc6ac4f03415cf4578ce946bce88'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'MD5' 'cca051e3ebc069e24b6e8b5c60d2fb2b'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'MD5' '5125ef82ce2d3960bac4d213486aeb8d'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'MD5' '53aa60913a3c7a378319a432d165e2c9'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'MD5' 'aa8d852ab11bf63c70b2e665dece2918'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'MD5' 'a64d9aa89d80edc28c5a4117b24de2db'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'MD5' '722343e2bd11798df1ecb8f550919a97'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'MD5' '9ff396962c70e97fef98017d0fc7f030'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'MD5' 'a9d8286af9d0e142372958f9771dba7d'
'tasmax_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tasmax/tasmax_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'MD5' '470173d591c87fc8366678a0db3147f3'
'huss_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' 'c0cec042cc81e481d14ac6d1bcdfdc90'
'huss_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' '7397ffe29520c308b7ce52a13fff67a5'
'huss_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' '39de4e2fd1cc09e517502c3aacf4b48c'
'huss_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' '06a6b1e8c71ba82cb1f4569bf269760b'
'huss_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' 'f8c02af89d384f18df6929d2ec21bff3'
'huss_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '38d32657932b583d9e0cf9fcde71deb1'
'huss_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'MD5' '4dc26fb3416c573452f4733fa8a18909'
'huss_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'MD5' 'ffc8f91f98a8bc3b146ae18f815d4de9'
'huss_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'MD5' '575a8c2187a87ffe08db5ed869d82947'
'huss_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'MD5' 'ca80c5ddfff878950691d9c24ee649e7'
'huss_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'MD5' 'fe80ddbf152f30566e1697aa73e789b7'
'huss_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'MD5' '11d33fba08b2557c7b5f1956142f63db'
'huss_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'MD5' 'af078bfc95ab9dbae49b91eda0deb387'
'huss_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'MD5' '1580fdcd8a9f50be99894d92c71961de'
'huss_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'MD5' '754f20d419a4fe4e8c1edc7e8fc703b1'
'huss_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/huss/huss_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'MD5' '2e7bfc6e52ef287e54163139c8c630cf'
'rlds_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rlds/rlds_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' '33a91bb18eeb882a9d8c0f5243f9cd32'
'rlds_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rlds/rlds_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' 'ca48a525587285e8d87e1ccccf95eb9c'
'rlds_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rlds/rlds_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' '2490013764febca5c2ad7a42f2f464e3'
'rlds_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rlds/rlds_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' '624132581aaac4c94da8782276764d25'
'rlds_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rlds/rlds_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' '4a8b5b156a04020683eab316b12ba867'
'rlds_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rlds/rlds_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '0fee665ef45c26c1c0ff9f7bf1cb910e'
'rsds_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rsds/rsds_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' 'ae85262ff974a1e0913588a9cda324af'
'rsds_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rsds/rsds_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' 'a509f83fb068f6eb5697937bc7b8db49'
'rsds_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rsds/rsds_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' 'b9e71b3a254e00bebbd66d3f92d89632'
'rsds_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rsds/rsds_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' 'f109b953c1db9ff7ca4bd56e505a5e43'
'rsds_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rsds/rsds_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' 'eb26bc818e283ea1f97f5055229cd0ea'
'rsds_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/rsds/rsds_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '73396297d36348085bd01777aafa3e4c'
'tas_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' 'cfb83b97970bbfddf45a815aaa82eb45'
'tas_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' '800c8a873067b63a9cba206aedb25d00'
'tas_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' 'f0edd0f19eb820d72b79db3a9db4c19a'
'tas_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' 'c56574a85dbee5b60a296bfccaf060ad'
'tas_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' '70de10569a27e539ac2e71cff266fcf2'
'tas_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '456e9fa56dafd72970242de50fba3ff5'
'tas_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'MD5' '42e207c35849c1ebaa61c51612f309d8'
'tas_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'MD5' '5509cfdf41a8803167756db28158e75d'
'tas_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'MD5' '430b7896822e89babf3d6a8a84910c8e'
'tas_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'MD5' '5381859136db0a24b943a171ab20dfdb'
'tas_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'MD5' '97f41c58b6bf16a150a7eece09ff3cbe'
'tas_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'MD5' '1ff58e1883991425a007043577f81c27'
'tas_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'MD5' '820ab37d3f526f788d8d37b99dd7e788'
'tas_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'MD5' 'ea332ed80802abc5bee84d318acc1600'
'tas_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'MD5' 'd22d0ab5ae57bd6ee97ebb0f26603959'
'tas_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/tas/tas_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'MD5' 'f58209d16b3bdf9ad25a16f896580e29'
'pr_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_20000101-20051231.nc' 'MD5' '9b5f2c8afe19272fd3a6dc0804f9c51b'
'pr_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19900101-19991231.nc' 'MD5' 'b7c4dd029c3b7a9a46c149fe1faed9a7'
'pr_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19800101-19891231.nc' 'MD5' '33a3727b3c341d56ffed0d17e402c664'
'pr_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19700101-19791231.nc' 'MD5' '704ed594187171f05d7b4def64e38be0'
'pr_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19600101-19691231.nc' 'MD5' '9ec005db24e3c769633bf74e3733c4fb'
'pr_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19500101-19591231.nc' 'MD5' '39349ecc316bdb14ad7b106f7694e482'
'pr_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19400101-19491231.nc' 'MD5' 'cf0a865df96d79b5029694c95023f979'
'pr_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19300101-19391231.nc' 'MD5' 'b5ea1c958e892290fc4ef6282855b5df'
'pr_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19200101-19291231.nc' 'MD5' '66393b2a2c380f28bc57ec10e143c838'
'pr_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19100101-19191231.nc' 'MD5' 'a9541aa24fc53a0bddd5e38f6570de0b'
'pr_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_19000101-19091231.nc' 'MD5' '1a2138bd0a4f95a480cb50b0154f62b8'
'pr_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_18900101-18991231.nc' 'MD5' '24a14bf0d222ba0743fe6a2f2ce38897'
'pr_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_18800101-18891231.nc' 'MD5' '847751f3e61d93e960ac5817d0d4064b'
'pr_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_18700101-18791231.nc' 'MD5' '2ea148346fb500cc1280e837470f435a'
'pr_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_18600101-18691231.nc' 'MD5' '8f93ada7bf6252e2da88b3f8ce9fb87b'
'pr_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'http://dias-esg-nd.tkl.iis.u-tokyo.ac.jp/thredds/fileServer/esg_dataroot/outgoing/output1/MRI/MRI-CGCM3/historical/day/atmos/day/r1i1p1/v20120701/pr/pr_day_MRI-CGCM3_historical_r1i1p1_18500101-18591231.nc' 'MD5' '2f92012732972f351e578a486175d108'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
TRUSTSTORE=$ESG_HOME/esg-truststore.ts
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java is required for retrieving the certificate and couldn't be found."
        exit 1
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if ((mVer<5)); then
        echo "Java version 1.5+ is required for retrieving the certificate." >&2
        echo "Current version seems older: $(java -version | head -n1) " >&2  
        exit 1
    fi
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

#get truststore from github
get_truststore() {
    # don't if this was already done today
    [[ -z $force && "$(find $TRUSTSTORE -type f -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Truststore..." >&2
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg-truststore.ts -O $TRUSTSTORE -q ; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg-truststore.ts -O $TRUSTSTORE
        echo "Could't update truststore!" >&2
        return 1
    else
        touch $TRUSTSTORE
    fi
    
    echo "done!" >&2    
}

# Retrieve ESG credentials
unset pass
get_credentials() {
    check_java
    #get all certificates
    get_certificates
    #get truststore 
    get_truststore
    
    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    
    #get password
    [[ ! "$pass" ]] && read -sp "MyProxy Password? " pass


    local args=
    [[ "$openId" ]] && args=$args" --oid $openId"
    [[ "$pass" ]] && args=$args" -P $pass"
    [[ "$username" ]] && args=$args" -l $username"
    
    echo -n $'\nRetrieving Credentials...' >&2
    if ! java $(proxy_to_java) -Djavax.net.ssl.trustStore=$TRUSTSTORE -Djavax.net.ssl.trustStorePassword=changeit -jar $MYPROXY_GETCERT $args --output $ESG_CREDENTIALS ; then        
        echo "Certificate could not be retrieved"
        exit 1
    fi
    echo "done!" >&2
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

get_mod_time_() {
    if ((LINUX)); then
        #on linux modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    elif ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 108 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
